const month = [
    {
        "MONTH_SEQ": 1,
        "MONTH_ID": "01",
        "MONTH_ABBR_TH": "ม.ค.",
        "MONTH_ABBR_EN": "Jan",
        "MONTH_NAME_TH": "มกราคม",
        "MONTH_NAME_EN": "January",
    },
    {
        "MONTH_SEQ": 2,
        "MONTH_ID": "02",
        "MONTH_ABBR_TH": "ก.พ.",
        "MONTH_ABBR_EN": "Feb",
        "MONTH_NAME_TH": "กุมภาพันธ์",
        "MONTH_NAME_EN": "February",
    },
    {
        "MONTH_SEQ": 3,
        "MONTH_ID": "03",
        "MONTH_ABBR_TH": "มี.ค.",
        "MONTH_ABBR_EN": "Mar",
        "MONTH_NAME_TH": "มีนาคม",
        "MONTH_NAME_EN": "March",
    },
    {
        "MONTH_SEQ": 4,
        "MONTH_ID": "04",
        "MONTH_ABBR_TH": "เม.ย.",
        "MONTH_ABBR_EN": "Apr",
        "MONTH_NAME_TH": "เมษายน",
        "MONTH_NAME_EN": "April",
    },
    {
        "MONTH_SEQ": 5,
        "MONTH_ID": "05",
        "MONTH_ABBR_TH": "พ.ค.",
        "MONTH_ABBR_EN": "May",
        "MONTH_NAME_TH": "พฤษภาคม",
        "MONTH_NAME_EN": "May",
    },
    {
        "MONTH_SEQ": 6,
        "MONTH_ID": "06",
        "MONTH_ABBR_TH": "มิ.ย.",
        "MONTH_ABBR_EN": "Jun",
        "MONTH_NAME_TH": "มิถุนายน",
        "MONTH_NAME_EN": "June",
    },
    {
        "MONTH_SEQ": 7,
        "MONTH_ID": "07",
        "MONTH_ABBR_TH": "ก.ค.",
        "MONTH_ABBR_EN": "Jul",
        "MONTH_NAME_TH": "กรกฎาคม",
        "MONTH_NAME_EN": "July",
    },
    {
        "MONTH_SEQ": 8,
        "MONTH_ID": "08",
        "MONTH_ABBR_TH": "ส.ค.",
        "MONTH_ABBR_EN": "Aug",
        "MONTH_NAME_TH": "สิงหาคม",
        "MONTH_NAME_EN": "August",
    },
    {
        "MONTH_SEQ": 9,
        "MONTH_ID": "09",
        "MONTH_ABBR_TH": "ก.ย.",
        "MONTH_ABBR_EN": "Sep",
        "MONTH_NAME_TH": "กันยายน",
        "MONTH_NAME_EN": "September",
    },
    {
        "MONTH_SEQ": 10,
        "MONTH_ID": "10",
        "MONTH_ABBR_TH": "ต.ค.",
        "MONTH_ABBR_EN": "Oct",
        "MONTH_NAME_TH": "ตุลาคม",
        "MONTH_NAME_EN": "October",
    },
    {
        "MONTH_SEQ": 11,
        "MONTH_ID": "11",
        "MONTH_ABBR_TH": "พ.ย.",
        "MONTH_ABBR_EN": "Nov",
        "MONTH_NAME_TH": "พฤศจิกายน",
        "MONTH_NAME_EN": "November",
    },
    {
        "MONTH_SEQ": 12,
        "MONTH_ID": "12",
        "MONTH_ABBR_TH": "ธ.ค.",
        "MONTH_ABBR_EN": "Dec",
        "MONTH_NAME_TH": "ธันวาคม",
        "MONTH_NAME_EN": "December",
    }
]

export default month 